baseURL = "paperarrow.netlify.com"
languageCode = "en-us"
title = "PaperArrow"
defaultContentLanguage = "en"
theme = ["hermit", "reveal-hugo"]
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Xavier Roy"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  audience = "audiences"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"
  homeSubtitle = "Notes and thoughts"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/xavierroy/cautious-barnacle/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  # Add custom css
  customCSS = ["/css/icons.css"]
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/paperarrow"
  [[params.social]]
    name = "github"
    url = "https://github.com/paperarrow"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "post/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "is/"
    weight = 20
  [[menu.main]]
    name= "Talks"
    url = "talks/"
    weight = 30


  [mediaTypes]
  [mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputs]
   home = [ "HTML", "Atom" ]

  [outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "index"
  isPlainText = false
 
 [outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true